main: me.brownie.inventoryrandomizer.InventoryRandomizer
name: Inventory_Randomizer
author: Brownie
version: 1.3
api-version: 1.17

commands:
  get:
    usage: /inventoryrandomizer get
  reload:
    usage: /inventoryrandomizer reload